apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    strimzi.io/use-connector-resources: 'true'
  creationTimestamp: '2022-07-28T21:30:02Z'
  generation: 28
  managedFields:
    - apiVersion: kafka.strimzi.io/v1beta2
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
          'f:connectorPlugins': {}
          'f:labelSelector': {}
          'f:observedGeneration': {}
          'f:replicas': {}
          'f:url': {}
      manager: okhttp
      operation: Update
      subresource: status
      time: '2022-08-01T17:41:27Z'
    - apiVersion: kafka.strimzi.io/v1beta2
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:strimzi.io/use-connector-resources': {}
        'f:spec':
          .: {}
          'f:bootstrapServers': {}
          'f:build':
            .: {}
            'f:output':
              .: {}
              'f:image': {}
              'f:type': {}
            'f:plugins': {}
          'f:config':
            'f:key.converter.apicurio.registry.converter.serializer': {}
            'f:key.converter.apicurio.registry.auto-register': {}
            'f:value.converter.apicurio.registry.url': {}
            'f:key.converter.apicurio.registry.as-confluent': {}
            'f:config.storage.topic': {}
            'f:offset.storage.replication.factor': {}
            'f:apicurio.registry.url': {}
            'f:status.storage.replication.factor': {}
            .: {}
            'f:value.converter.apicurio.registry.converter.serializer': {}
            'f:value.converter': {}
            'f:key.converter.apicurio.registry.url': {}
            'f:value.converter.apicurio.registry.as-confluent': {}
            'f:value.converter.apicurio.registry.auto-register': {}
            'f:status.storage.topic': {}
            'f:offset.storage.topic': {}
            'f:config.storage.replication.factor': {}
            'f:key.converter': {}
            'f:group.id': {}
          'f:replicas': {}
          'f:tls':
            .: {}
            'f:trustedCertificates': {}
          'f:version': {}
      manager: Mozilla
      operation: Update
      time: '2022-08-01T19:30:35Z'
  name: my-connect-cluster
  namespace: amq-streams
  resourceVersion: '30545682'
  uid: b0557d3e-a90d-449e-a507-186c1cd77ef6
spec:
  bootstrapServers: 'my-cluster-kafka-bootstrap:9093'
  build:
    output:
      image: 'debezium-streams-connect:lastest'
      type: imagestream
    plugins:
      - artifacts:
          - type: jar
            url: >-
              https://maven.repository.redhat.com/ga/io/apicurio/apicurio-registry-serdes-jsonschema-serde/2.0.0.Final-redhat-00005/apicurio-registry-serdes-jsonschema-serde-2.0.0.Final-redhat-00005.jar
          - type: jar
            url: >-
              https://maven.repository.redhat.com/ga/io/apicurio/apicurio-registry-serdes-avro-serde/2.0.3.Final-redhat-00002/apicurio-registry-serdes-avro-serde-2.0.3.Final-redhat-00002.jar
          - type: jar
            url: >-
              https://maven.repository.redhat.com/ga/io/apicurio/apicurio-registry-serdes-protobuf-serde/2.0.3.Final-redhat-00002/apicurio-registry-serdes-protobuf-serde-2.0.3.Final-redhat-00002.jar
          - type: jar
            url: >-
              https://maven.repository.redhat.com/ga/io/apicurio/apicurio-registry-rest-client/1.3.2.Final-redhat-00015/apicurio-registry-rest-client-1.3.2.Final-redhat-00015.jar
          - type: jar
            url: >-
              https://maven.repository.redhat.com/ga/io/apicurio/apicurio-registry-client/2.0.3.Final-redhat-00002/apicurio-registry-client-2.0.3.Final-redhat-00002.jar
          - type: jar
            url: >-
              https://maven.repository.redhat.com/ga/io/apicurio/apicurio-registry-serde-common/2.0.3.Final-redhat-00002/apicurio-registry-serde-common-2.0.3.Final-redhat-00002.jar
          - type: jar
            url: >-
              https://maven.repository.redhat.com/ga/io/apicurio/apicurio-registry-common/2.0.3.Final-redhat-00002/apicurio-registry-common-2.0.3.Final-redhat-00002.jar
          - type: jar
            url: >-
              https://maven.repository.redhat.com/ga/org/keycloak/keycloak-authz-client/18.0.0.redhat-00001/keycloak-authz-client-18.0.0.redhat-00001.jar
          - type: jar
            url: >-
              https://maven.repository.redhat.com/ga/org/apache/httpcomponents/httpclient/4.5.13.redhat-00002/httpclient-4.5.13.redhat-00002.jar
          - type: jar
            url: >-
              https://maven.repository.redhat.com/ga/org/apache/httpcomponents/httpcore/4.4.15.redhat-00002/httpcore-4.4.15.redhat-00002.jar
          - type: zip
            url: >-
              https://maven.repository.redhat.com/ga/io/debezium/debezium-connector-postgres/1.9.5.Final-redhat-00001/debezium-connector-postgres-1.9.5.Final-redhat-00001-plugin.zip
          - type: zip
            url: >-
              https://maven.repository.redhat.com/ga/io/apicurio/apicurio-registry-distro-connect-converter/1.2.2.Final-redhat-00005/apicurio-registry-distro-connect-converter-1.2.2.Final-redhat-00005-converter.zip
        name: debezium-connector-postgresql
  config:
    apicurio.registry.url: 'http://service-registry-service.service-registry.svc.cluster.local:8080'
    status.storage.topic: connect-cluster-status
    status.storage.replication.factor: -1
    offset.storage.topic: connect-cluster-offsets
    key.converter.apicurio.registry.url: >-
      http://service-registry.service-registry.router-default.apps.os.pietersmalan.com
    value.converter: io.apicurio.registry.utils.converter.AvroConverter
    value.converter.apicurio.registry.auto-register: true
    group.id: connect-cluster
    key.converter.apicurio.registry.converter.serializer: io.apicurio.registry.serde.avro.AvroKafkaSerializer
    key.converter.apicurio.registry.as-confluent: true
    config.storage.replication.factor: -1
    config.storage.topic: connect-cluster-configs
    key.converter: io.apicurio.registry.utils.converter.AvroConverter
    key.converter.apicurio.registry.auto-register: true
    value.converter.apicurio.registry.url: >-
      http://service-registry.service-registry.router-default.apps.os.pietersmalan.com
    value.converter.apicurio.registry.converter.serializer: io.apicurio.registry.serde.avro.AvroKafkaSerializer
    value.converter.apicurio.registry.as-confluent: true
    offset.storage.replication.factor: -1
  replicas: 1
  tls:
    trustedCertificates:
      - certificate: ca.crt
        secretName: my-cluster-cluster-ca-cert
  version: 3.1.0
